import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1A1D2E', // Dark background
    },
    androidSafeArea: {
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    closeButton: {
        alignSelf: 'flex-end',
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    closeButtonText: {
        fontSize: 20,
        color: '#FFF',
        fontWeight: '600',
    },
    scrollContent: {
        paddingTop: 20,
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '700',
        fontFamily: 'Lexend',
        color: '#FFFFFF',
        textAlign: 'center',
        marginBottom: 12,
    },
    headerSubtitle: {
        fontSize: 16,
        color: '#A0A0A0',
        fontFamily: 'Lexend',
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 32,
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 12,
        padding: 4,
        marginBottom: 32,
    },
    toggleButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    toggleButtonActive: {
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    toggleButtonText: {
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Lexend',
        color: '#A0A0A0',
    },
    toggleButtonTextActive: {
        color: '#FFFFFF',
    },
    plansWrapper: {
        marginBottom: 32,
    },
    planCardVertical: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    planCardVerticalSelected: {
        backgroundColor: 'rgba(255,107,53,0.1)',
        borderColor: '#FF6B35',
    },
    planCardContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    radioButtonLeft: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#666',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    radioButtonLeftSelected: {
        borderColor: '#FF6B35',
    },
    radioButtonLeftInner: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: '#FF6B35',
    },
    planCardInfo: {
        flex: 1,
    },
    planTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    planTitle: {
        fontSize: 20,
        fontWeight: '700',
        fontFamily: 'Lexend',
        color: '#FFFFFF',
        marginRight: 12,
    },
    popularBadge: {
        backgroundColor: '#FF6B35',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    popularBadgeText: {
        fontSize: 11,
        fontWeight: '700',
        fontFamily: 'Lexend',
        color: '#FFFFFF',
    },
    planSubtitle: {
        fontSize: 14,
        color: '#A0A0A0',
        fontFamily: 'Lexend',
    },
    planPriceContainer: {
        alignItems: 'flex-end',
    },
    planPriceAmount: {
        fontSize: 28,
        fontWeight: '700',
        fontFamily: 'Lexend',
        color: '#FFFFFF',
    },
    planPricePeriod: {
        fontSize: 16,
        color: '#A0A0A0',
        fontFamily: 'Lexend',
    },
    featuresSection: {
        marginBottom: 32,
    },
    featuresTitle: {
        fontSize: 18,
        fontWeight: '700',
        fontFamily: 'Lexend',
        color: '#FFFFFF',
        marginBottom: 16,
    },
    featureItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    featureCheckmark: {
        fontSize: 18,
        color: '#4CAF50',
        marginRight: 12,
        fontWeight: '700',
    },
    featureText: {
        fontSize: 16,
        color: '#E0E0E0',
        fontFamily: 'Lexend',
    },
    trialInfo: {
        fontSize: 14,
        color: '#A0A0A0',
        fontFamily: 'Lexend',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
    ctaButtonNew: {
        backgroundColor: '#FFFFFF',
        paddingVertical: 18,
        paddingHorizontal: 24,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    ctaButtonTextNew: {
        color: '#1A1D2E',
        fontSize: 18,
        fontWeight: '700',
        fontFamily: 'Lexend',
        textAlign: 'center',
    },
    freeTrialButtonNew: {
        backgroundColor: 'transparent',
        paddingVertical: 18,
        paddingHorizontal: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.2)',
        marginTop: 16,
    },
    freeTrialButtonTextNew: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '700',
        fontFamily: 'Lexend',
        textAlign: 'center',
    },
});
